/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplecalculator;

/**
 *
 * @author Andrey
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPane1 = new javax.swing.JPanel();
        number1 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        jres = new javax.swing.JTextField();
        jmult = new javax.swing.JButton();
        jdibide = new javax.swing.JButton();
        TT1 = new javax.swing.JLabel();
        TT2 = new javax.swing.JLabel();
        TT3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmult.setText("Умножить");
        jmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmultActionPerformed(evt);
            }
        });

        jdibide.setText("Разделить");
        jdibide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdibideActionPerformed(evt);
            }
        });

        TT1.setText("Число 1");

        TT2.setText("Число 2");

        TT3.setText("Разделить");

        javax.swing.GroupLayout jPane1Layout = new javax.swing.GroupLayout(jPane1);
        jPane1.setLayout(jPane1Layout);
        jPane1Layout.setHorizontalGroup(
            jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdibide)
                    .addComponent(jmult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPane1Layout.createSequentialGroup()
                        .addComponent(jres, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPane1Layout.createSequentialGroup()
                        .addComponent(TT3)
                        .addGap(57, 57, 57))))
            .addGroup(jPane1Layout.createSequentialGroup()
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(TT1)
                        .addGap(67, 67, 67)
                        .addComponent(TT2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPane1Layout.setVerticalGroup(
            jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT1)
                    .addComponent(TT2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jmult))
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(TT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdibide)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdibideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdibideActionPerformed
        String inputText = number1.getText();
        double a = 0; 
        try {
            a = Double.parseDouble(inputText);
        } catch (NumberFormatException e) {
            System.out.println("Введите корректное число.");
        }
        System.out.println("Значение a: " + a);
        
        String inputText2 = number2.getText();
        double b = 0; 
        try {
            b = Double.parseDouble(inputText2);
        } catch (NumberFormatException e) {
            System.out.println("Введите корректное число.");
        }
        System.out.println("Значение b: " + b);
        
        Calculator calculator = new Calculator();
        double result = calculator.divide(a, b);
        jres.setText(String.valueOf(result));
    }//GEN-LAST:event_jdibideActionPerformed

    private void jmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmultActionPerformed
        String inputText = number1.getText();
        double a = 0; 
        try {
            a = Double.parseDouble(inputText);
        } catch (NumberFormatException e) {
            System.out.println("Введите корректное число.");
        }
        System.out.println("Значение a: " + a);
        
        String inputText2 = number2.getText();
        double b = 0; 
        try {
            b = Double.parseDouble(inputText2);
        } catch (NumberFormatException e) {
            System.out.println("Введите корректное число.");
        }
        System.out.println("Значение b: " + b);
        
        Calculator calculator = new Calculator();
        double result = calculator.multiply(a, b);
        jres.setText(String.valueOf(result));
    }//GEN-LAST:event_jmultActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TT1;
    private javax.swing.JLabel TT2;
    private javax.swing.JLabel TT3;
    private javax.swing.JPanel jPane1;
    private javax.swing.JButton jdibide;
    private javax.swing.JButton jmult;
    private javax.swing.JTextField jres;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    // End of variables declaration//GEN-END:variables
}
