/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplecalculator;

/**
 *

public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


  
        jPane1 = new javax.swing.JPanel();
        number1 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        jres = new javax.swing.JTextField();
        jmult = new javax.swing.JButton();
        jdibide = new javax.swing.JButton();
        TT1 = new javax.swing.JLabel();
        TT2 = new javax.swing.JLabel();
        TT3 = new javax.swing.JLabel();
        jAdd = new javax.swing.JButton();
        jSubtract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmult.setText("Óìíîæèòü");
        jmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmultActionPerformed(evt);
            }
        });

        jdibide.setText("Ðàçäåëèòü");
        jdibide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdibideActionPerformed(evt);
            }
        });
      
        jAdd.setText("Ñëîæåíèå");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jSubtract.setText("Âû÷èòàíèå");
        jSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubtractActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(t2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t3)
                    .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))

        );
        jPane1Layout.setVerticalGroup(
            jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT1)
                    .addComponent(TT2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jmult))
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(TT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdibide)
                .addContainerGap(116, Short.MAX_VALUE))

        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jdibideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdibideActionPerformed
        String inputText = number1.getText();

        double a = 0; 
        try {
            a = Double.parseDouble(inputText);
        } catch (NumberFormatException e) {
            System.out.println("Ââåäèòå êîððåêòíîå ÷èñëî.");
        }
        System.out.println("Çíà÷åíèå a: " + a);
        

        String inputText2 = number2.getText();

        double b = 0; 
        try {
            b = Double.parseDouble(inputText2);
        } catch (NumberFormatException e) {
            System.out.println("Ââåäèòå êîððåêòíîå ÷èñëî.");
        }
        System.out.println("Çíà÷åíèå b: " + b);
        
        Calculator calculator = new Calculator();

        double result = calculator.divide(a, b);
        jres.setText(String.valueOf(result));
    }//GEN-LAST:event_jdibideActionPerformed

    private void jmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmultActionPerformed
        String inputText = number1.getText();

        double a = 0; 
        try {
            a = Double.parseDouble(inputText);
        } catch (NumberFormatException e) {
            System.out.println("Ââåäèòå êîððåêòíîå ÷èñëî.");
        }
        System.out.println("Çíà÷åíèå a: " + a);
        

        String inputText2 = number2.getText();

        double b = 0; 
        try {
            b = Double.parseDouble(inputText2);
        } catch (NumberFormatException e) {
            System.out.println("Ââåäèòå êîððåêòíîå ÷èñëî.");
        }
        System.out.println("Çíà÷åíèå b: " + b);
        
        Calculator calculator = new Calculator();

        double result = calculator.multiply(a, b);
        jres.setText(String.valueOf(result));
    }//GEN-LAST:event_jmultActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TT1;
    private javax.swing.JLabel TT2;
    private javax.swing.JLabel TT3;
    private javax.swing.JPanel jPane1;
    private javax.swing.JButton jdibide;
    private javax.swing.JButton jmult;
    private javax.swing.JTextField jres;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;

    // End of variables declaration//GEN-END:variables
}
